version: '3.8'

services:
  # Development environment
  app-dev:
    profiles: ["dev"]
    build:
      context: .
      target: builder
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: pnpm dev
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  # Production environment
  app-prod:
    profiles: ["prod"]
    build:
      context: .
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx reverse proxy for production
  nginx:
    profiles: ["prod"]
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 